### ISSUE TITLE
PERMISSIONS

### ISSUE THREAD

**Issue by CaiIsProgrammer** [BrendonCurmi/FxBiomeRTP#17]
Hey,
so this is better than any rtp and causes lil lag. but players can tp any other players.

**Comment by BrendonCurmi** [comment]
Hi. Thanks. What do you mean players can tp to other players? This plugin doesn't have a /tp command to teleport. Only /rtp and /biomertp. Perhaps it's another plugin causing the tp issue

**Comment by BrendonCurmi** [comment]
Understood, thanks, will cover in #18
